# Generated by Django 4.0 on 2022-03-14 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('notes', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
